### ISSUE TITLE
运行出错，大佬排查下

### ISSUE THREAD

**Issue by Darkoutput** [NICHX/kaoshibao#1]
运行系统：Windows10
运行平台：PyCharm2024.1\python3.12
运行代码：最新fix
出错警告：Traceback (most recent call last):
  File "D:\下载\kaoshibao-crack\main.py", line 78, in <module>
    main_window()
  File "C:\Users\a\AppData\Local\Programs\Python\Python312\Lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\下载\kaoshibao-crack\main.py", line 33, in main_window
    download_ques(args.题目数量, args.题库ID, args.保存目录, args.保存文件名)
  File "D:\下载\kaoshibao-crack\main.py", line 54, in download_ques
    formatted_option = "\n".join(
                       ^^^^^^^^^^
  File "D:\下载\kaoshibao-crack\main.py", line 55, in <genexpr>
    f"{line[0]}. {line[1:]}" if line[0].isupper() else line for line in option.splitlines())
                                ~~~~^^^
IndexError: string index out of range

<img width="1231" alt="image" src="https://github.com/NICHX/kaoshibao/assets/77570061/95d44a32-55dc-47fe-912b-f633be7d8f27">

**Comment by NICHX** [comment]
能提供下题库ID吗

**Comment by Darkoutput** [comment]
> 能提供下题库ID吗

题库ID:9194448
运行出错：最新出错为第343题（多次测试，不规律出现，报错代码一样）
希望增加功能：题目（例如题库ID为11529715为第72,73题）、答案（例如题库ID为9194448的第1、23题）存在图片，希望保存时也一起保存下来

**Comment by NICHX** [comment]
> > 能提供下题库ID吗
> 
> 题库ID:9194448 运行出错：最新出错为第343题（多次测试，不规律出现，报错代码一样） 希望增加功能：题目（例如题库ID为11529715为第72,73题）、答案（例如题库ID为9194448的第1、23题）存在图片，希望保存时也一起保存下来

未能复现问题
![image](https://github.com/NICHX/kaoshibao/assets/24547848/459a0146-5366-430b-9928-be205508783c)
